import { useMemo, useState } from 'react';
import { ChevronDown, Clipboard, MessageCircleQuestion, Search } from 'lucide-react';

interface GuideItem { id: number; category: string; complaint: string; explanation: string; script: string; }

const GUIDE_ITEMS: GuideItem[] = [
  { id: 1, category: 'Bateria', complaint: 'Bateria descarrega rápido após a troca', explanation: 'Uma bateria nova precisa de alguns ciclos de carga para calibrar. Aplicativos em segundo plano, sinal fraco e configurações que consomem muita energia também podem afetar os primeiros dias de uso.', script: '“Entendo sua preocupação. A bateria nova ainda está calibrando e o celular também se adapta ao seu uso. Vamos verificar o consumo juntos e garantir que nenhum aplicativo ou componente esteja causando o descarregamento.”' },
  { id: 2, category: 'Tela', complaint: 'A tela substituída parece diferente', explanation: 'Painéis originais, OLED e Incell usam tecnologias diferentes de brilho, cor e toque. A qualidade da peça substituída deve ser sempre confirmada antes da aprovação.', script: '“Existem diferentes tecnologias de tela para este modelo. Esta peça oferece o melhor equilíbrio entre preço e desempenho, e posso mostrar as opções de qualidade antes de continuar.”' },
  { id: 3, category: 'Reparo de Placa', complaint: 'Por que o reparo de placa demora tanto?', explanation: 'Reparos de placa exigem diagnóstico sob lupa, teste de componentes e solda controlada. O primeiro diagnóstico pode revelar danos adicionais que não eram visíveis por fora.', script: '“O trabalho de placa é um diagnóstico detalhado, não uma simples troca de peça. Testamos o circuito passo a passo para não trocar peças desnecessariamente. Vou atualizar você assim que tivermos um caminho seguro de reparo.”' },
  { id: 4, category: 'Garantia', complaint: 'O problema voltou durante a garantia', explanation: 'A garantia cobre o defeito reparado nas condições acordadas, mas dano por líquido, impacto, manipulação indevida ou um defeito diferente podem mudar a avaliação.', script: '“Vamos avaliar pela garantia primeiro. A garantia cobre o serviço que realizamos, então vamos documentar se é o mesmo problema ou uma nova causa antes de sugerir qualquer custo.”' },
  { id: 5, category: 'Bateria', complaint: 'O celular esquenta enquanto carrega', explanation: 'Calor moderado pode ser normal durante o carregamento, especialmente com carregadores rápidos. Calor excessivo, inchaço ou cheiro de queimado exige desconexão imediata e inspeção.', script: '“Um pouco de calor pode ser normal com carregamento rápido, mas calor excessivo não é algo que ignoramos. Por favor, pare de usar esse carregador por enquanto e vamos inspecionar a bateria e o circuito de carga com segurança.”' },
  { id: 6, category: 'Tela', complaint: 'O toque não funciona em uma área', explanation: 'Uma zona morta no toque pode vir de um painel defeituoso, pressão de instalação ou problema no conector. Deve ser testado com uma grade antes da entrega final.', script: '“Obrigado por nos avisar. Vamos rodar o teste de toque em toda a tela e corrigir a instalação ou trocar a peça se o painel estiver defeituoso.”' },
];

const CATEGORIES = ['Todos', 'Bateria', 'Tela', 'Reparo de Placa', 'Garantia'];

export function FaqPage() {
  const [search, setSearch] = useState('');
  const [category, setCategory] = useState('Todos');
  const [openId, setOpenId] = useState<number | null>(1);
  const [copiedId, setCopiedId] = useState<number | null>(null);
  const filtered = useMemo(() => GUIDE_ITEMS.filter((item) => {
    const term = search.toLowerCase().trim();
    return (!term || `${item.complaint} ${item.explanation} ${item.script}`.toLowerCase().includes(term)) && (category === 'Todos' || item.category === category);
  }), [search, category]);
  const copyScript = async (item: GuideItem) => { await navigator.clipboard.writeText(item.script); setCopiedId(item.id); window.setTimeout(() => setCopiedId(null), 1600); };

  return <div className="space-y-6">
    <div className="rounded-2xl border border-blue-100 dark:border-blue-500/20 bg-blue-50 dark:bg-blue-500/10 p-5 sm:p-6"><div className="flex items-start gap-4"><div className="hidden sm:flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-blue-600 text-white"><MessageCircleQuestion size={22} /></div><div><p className="text-sm font-semibold text-blue-700 dark:text-blue-400">Guia do balcão</p><h2 className="text-xl font-bold text-slate-900 dark:text-white mt-1">Respostas claras constroem confiança</h2><p className="text-sm text-slate-600 dark:text-slate-300 mt-1.5 max-w-2xl">Use a explicação técnica para entender o problema e depois copie o roteiro sugerido para manter a conversa calma e consistente.</p></div></div></div>
    <div className="flex flex-col gap-3"><div className="relative"><Search size={18} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Buscar reclamações, explicações ou roteiros..." className="w-full rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 pl-10 pr-4 py-3 text-sm text-slate-900 dark:text-white placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-blue-500" /></div><div className="flex gap-2 overflow-x-auto pb-1">{CATEGORIES.map((item) => <button key={item} onClick={() => setCategory(item)} className={`whitespace-nowrap rounded-lg px-3.5 py-2 text-xs font-semibold transition-colors ${category === item ? 'bg-blue-600 text-white' : 'bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 text-slate-600 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-800'}`}>{item}</button>)}</div></div>
    <div className="space-y-3">{filtered.length === 0 ? <div className="rounded-2xl border border-dashed border-slate-300 dark:border-slate-700 py-16 text-center text-sm text-slate-500">Nenhuma entrada do guia corresponde à sua busca.</div> : filtered.map((item) => { const open = openId === item.id; return <div key={item.id} className="overflow-hidden rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900"><button onClick={() => setOpenId(open ? null : item.id)} className="flex w-full items-center gap-3 px-4 sm:px-5 py-4 text-left"><span className="rounded-md bg-slate-100 dark:bg-slate-800 px-2 py-1 text-[10px] font-bold uppercase tracking-wide text-slate-500 dark:text-slate-400">{item.category}</span><span className="flex-1 text-sm font-semibold text-slate-900 dark:text-white">{item.complaint}</span><ChevronDown size={18} className={`shrink-0 text-slate-400 transition-transform ${open ? 'rotate-180' : ''}`} /></button>{open && <div className="border-t border-slate-100 dark:border-slate-800 px-4 sm:px-5 py-4 space-y-4"><div><p className="text-[11px] font-bold uppercase tracking-wide text-slate-400 mb-1.5">Explicação técnica</p><p className="text-sm leading-6 text-slate-600 dark:text-slate-300">{item.explanation}</p></div><div className="rounded-xl border border-blue-100 dark:border-blue-500/20 bg-blue-50/60 dark:bg-blue-500/10 p-4"><div className="flex items-center justify-between gap-3 mb-2"><p className="text-[11px] font-bold uppercase tracking-wide text-blue-700 dark:text-blue-400">Roteiro sugerido</p><button onClick={() => copyScript(item)} className="inline-flex items-center gap-1.5 text-xs font-semibold text-blue-700 dark:text-blue-400 hover:text-blue-900 dark:hover:text-blue-300"><Clipboard size={13} />{copiedId === item.id ? 'Copiado' : 'Copiar'}</button></div><p className="text-sm leading-6 font-medium text-slate-700 dark:text-slate-200">{item.script}</p></div></div>}</div>; })}</div>
  </div>;
}
